// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSWxCZLDcF-BWqvhm0hW_AOSI7o3iyw94',
    appId: '1:289444002346:web:ab32be0eac92a202832153',
    messagingSenderId: '289444002346',
    projectId: 'deenthusiast-2322d',
    authDomain: 'deenthusiast-2322d.firebaseapp.com',
    storageBucket: 'deenthusiast-2322d.firebasestorage.app',
    measurementId: 'G-6V2MSQPQ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_QQd8CS6skHHxxLbuAs-l-VgunWBHEZ8',
    appId: '1:289444002346:android:aba5a4b519fdc482832153',
    messagingSenderId: '289444002346',
    projectId: 'deenthusiast-2322d',
    storageBucket: 'deenthusiast-2322d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2xpnSVkdt66F6rBRmxE84DGMu0sA291M',
    appId: '1:289444002346:ios:3983a5aa0fdf3178832153',
    messagingSenderId: '289444002346',
    projectId: 'deenthusiast-2322d',
    storageBucket: 'deenthusiast-2322d.firebasestorage.app',
    iosBundleId: 'com.example.deenthusiast',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2xpnSVkdt66F6rBRmxE84DGMu0sA291M',
    appId: '1:289444002346:ios:3983a5aa0fdf3178832153',
    messagingSenderId: '289444002346',
    projectId: 'deenthusiast-2322d',
    storageBucket: 'deenthusiast-2322d.firebasestorage.app',
    iosBundleId: 'com.example.deenthusiast',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCSWxCZLDcF-BWqvhm0hW_AOSI7o3iyw94',
    appId: '1:289444002346:web:fbd68bacd1223404832153',
    messagingSenderId: '289444002346',
    projectId: 'deenthusiast-2322d',
    authDomain: 'deenthusiast-2322d.firebaseapp.com',
    storageBucket: 'deenthusiast-2322d.firebasestorage.app',
    measurementId: 'G-S53E3T8JN8',
  );

}